version: "3"
services:
  api-test:
    build:
      dockerfile: Dockerfile.prod
      target: build
      context: ./api
    container_name: api-test
    environment:
      - SPRING_PROFILES_ACTIVE=integration-test
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=my_password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-test:5432/quizstream_db_test
      - JWT_SECRET="bQeThWmZq4t7w!z$C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdSgVkYp3s6v9y$B&E)"
    command: mvn test
    depends_on:
      - postgres-test
  postgres-test:
    image: andreasx42/quizstream-postgres:latest
    container_name: postgres-test
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=quizstream_db_test
    restart: always
