version: "3"
services:
  backend-test:
    build:
      dockerfile: Dockerfile.prod
      context: ./backend
    container_name: backend-test
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DATABASE=quizstream_db_test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_HOST=postgres-test
      - POSTGRES_PORT=5432
      - POSTGRES_DRIVER=psycopg
      - EXECUTION_CONTEXT=test
    depends_on:
      - postgres-test
    restart: always
  postgres-test:
    image: andreasx42/quizstream-postgres:latest
    container_name: postgres-test
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=quizstream_db_test
    restart: always
