version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/qs_backend/backend/
    environment:
      - POSTGRES_DATABASE=quizstream_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DRIVER=psycopg
    depends_on:
      - postgres
    restart: always
  postgres:
    build:
      dockerfile: Dockerfile
      context: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=quizstream_db
    restart: always