services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./springboot_api
    container_name: api
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - ./springboot_api:/api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/quizstreamdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=my_password
      - SERVER_PORT=9090
      - JWT_SECRET="bQeThWmZq4t7w!z$C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdSgVkYp3s6v9y$B&E)"
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true
      - SPRING_PROFILES_ACTIVE=dev
      - APP_HOST=http://localhost:4200
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
    depends_on:
      - postgres
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./quiz_generator
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./quiz_generator:/qs_backend/backend/
    env_file:
      - .env
    environment:
      - POSTGRES_DATABASE=quizstreamdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DRIVER=psycopg
    depends_on:
      - postgres
    restart: always
  postgres:
    build:
      dockerfile: Dockerfile
      context: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=quizstreamdb
    restart: always