version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend/
    environment:
      - POSTGRES_DATABASE=postgres_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DRIVER=psycopg
    restart: always
  postgres:
    build:
      dockerfile: Dockerfile
      context: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
    restart: always
  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=my_password
    ports:
      - "5050:80"
    restart: always
