  version: "3"
  services:
    app:
      build:
        context: ./app
        dockerfile: Dockerfile.dev
      container_name: app
      ports:
        - "4200:4200"
      volumes:
        - ./app:/app
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true
    api:
      build:
        dockerfile: Dockerfile.dev
        context: ./api
      container_name: api
      ports:
        - "9090:9090"
      volumes:
        - ./api:/api
        - /api/target
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/quizstream_db
        - SPRING_DATASOURCE_USERNAME=admin
        - SPRING_DATASOURCE_PASSWORD=my_password
        - SERVER_PORT=9090
        - JWT_SECRET="bQeThWmZq4t7w!z$C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdSgVkYp3s6v9y$B&E)"
      depends_on:
        - postgres
    postgres:
      build:
        dockerfile: Dockerfile
        context: ./postgres
      container_name: postgres
      ports:
        - "5432:5432"
      volumes:
        - ./postgres/data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=my_password
        - POSTGRES_DB=quizstream_db
      restart: always
    pgadmin:
      image: dpage/pgadmin4:8.10
      container_name: pgadmin
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=my_password
      ports:
        - "5050:80"
      restart: always