FROM python:3.11-slim

EXPOSE 8080

WORKDIR /qs_backend

COPY ./requirements.txt ./

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./ ./backend

ENV PYTHONPATH="${PYTHONPATH}:/qs_backend"

CMD ["uvicorn", "backend.api:app", "--host", "0.0.0.0", "--port", "8080"]
