version: 2.1

executors:
  python-docker-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  # first we build and push the new Docker images to Docker Hub
  push_app_image:
    executor: python-docker-executor
    steps:
      - checkout
      - set_env_vars
      - docker_login
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Inject build info into frontend
          command: |
            FORMATTED_DATE = $(date +"%-d, %B, %Y %H:%M")
            sed -i "s/\$BUILD_NUMBER/${PIPELINE_NUMBER}/g" ./app/src/app/about/about.component.html
            sed -i "s/\$BUILD_DATE/${FORMATTED_DATE}/g" ./app/src/app/about/about.component.html
            sed -i "s/\$GIT_SHA/${TAG}/g" ./app/src/app/about/about.component.html
            sed -i "s/\API_URL/${API_URL}/g" ./app/src/app/shared/environment/environment.ts
            sed -i "s/\API_KEY/${API_KEY}/g" ./app/src/app/shared/environment/environment.ts
      - run:
          name: Push Angular app image
          command: |
            docker build -t $DOCKER_USER/$IMAGE_NAME_BASE-app:$TAG -t $DOCKER_USER/$IMAGE_NAME_BASE-app:latest -f ./app/Dockerfile.prod.todo ./app
            docker push $DOCKER_USER/$IMAGE_NAME_BASE-app:$TAG
            docker push $DOCKER_USER/$IMAGE_NAME_BASE-app:latest
  push_api_image:
    executor: python-docker-executor
    steps:
      - checkout
      - set_env_vars
      - docker_login
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Push Spring Boot api image
          command: |
            docker build -t $DOCKER_USER/$IMAGE_NAME_BASE-api:$TAG -t $DOCKER_USER/$IMAGE_NAME_BASE-api:latest -f ./api/Dockerfile.prod ./api
            docker push $DOCKER_USER/$IMAGE_NAME_BASE-api:$TAG
            docker push $DOCKER_USER/$IMAGE_NAME_BASE-api:latest
  push_backend_image:
    executor: python-docker-executor
    steps:
      - checkout
      - set_env_vars
      - docker_login
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Push Python backend image
          command: |
            docker build -t $DOCKER_USER/$IMAGE_NAME_BASE-backend:$TAG -t $DOCKER_USER/$IMAGE_NAME_BASE-backend:latest -f ./backend/Dockerfile.prod ./backend
            docker push $DOCKER_USER/$IMAGE_NAME_BASE-backend:$TAG
            docker push $DOCKER_USER/$IMAGE_NAME_BASE-backend:latest

  # not necessary to everytime push postgres image because it does not change
  # push_postgres_image:
  #   executor: python-docker-executor
  #   steps:
  #     - checkout
  #     - set_env_vars
  #     - docker_login
  #     - setup_remote_docker:
  #         docker_layer_caching: false
  #     - run:
  #         name: Push Postgres image
  #         command: |
  #           docker build -t $DOCKER_USER/$IMAGE_NAME_BASE-postgres:$TAG -t $DOCKER_USER/$IMAGE_NAME_BASE-postgres:latest ./postgres
  #           docker push $DOCKER_USER/$IMAGE_NAME_BASE-postgres:$TAG
  #           docker push $DOCKER_USER/$IMAGE_NAME_BASE-postgres:latest

  # then we run tests on the new Docker images
  # run_integration_tests:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run:
  #         name: Clear Docker cache
  #         command: docker system prune --all --force --volumes
  #     - run:
  #         name: Run Docker Compose to build, start and test
  #         command: |
  #           docker-compose -f docker-compose.integration.test.yaml up --exit-code-from test-suite
  #     - run:
  #         name: Shut services down
  #         command: docker-compose -f docker-compose.integration.test.yaml down
  #     - store_artifacts:
  #         path: /tests/test-reports
  #         destination: test-reports

  # if everything was successful we deploy the Docker images into the k8s cluster
  deploy_to_gke_k8s_cluster:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - set_env_vars
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo "$GOOGLE_SERVICE_KEY" > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project "$GOOGLE_PROJECT_ID"
            gcloud config set compute/zone "$GOOGLE_COMPUTE_ZONE"
            gcloud container clusters get-credentials "$GKE_CLUSTER_NAME"
      - run:
          name: Deploy to GKE k8s cluster
          command: |
            kubectl apply -f ./k8s
            kubectl set image deployments/app-deployment quizstream-app=$DOCKER_USER/$IMAGE_NAME_BASE-app:$TAG
            kubectl set image deployments/api-deployment quizstream-api=$DOCKER_USER/$IMAGE_NAME_BASE-api:$TAG
            kubectl set image deployments/backend-deployment quizstream-backend=$DOCKER_USER/$IMAGE_NAME_BASE-backend:$TAG

workflows:
  version: 2
  build-deploy:
    jobs:
      - push_app_image
      - push_api_image
      - push_backend_image
      # - push_postgres_image
      # - run_integration_tests:
      #     requires:
      #       - push_app_image
      #       - push_api_image
      #       - push_backend_image
      #       - push_postgres_image
      - deploy_to_gke_k8s_cluster:
          requires:
            - push_app_image
            - push_api_image
            - push_backend_image
            # - push_postgres_image

commands:
  set_env_vars:
    steps:
      - run:
          name: Setup tag and base image name
          command: |
            echo 'export TAG=${CIRCLE_SHA1:0:8}' >> $BASH_ENV
            echo 'export IMAGE_NAME_BASE=quizstream' >> $BASH_ENV
            echo 'export NOW=$(date --utc +"%Y-%m-%d %H:%M:%S")' >> $BASH_ENV
            echo 'export PIPELINE_NUMBER=<< pipeline.number >>' >> $BASH_ENV
  docker_login:
    steps:
      - run:
          name: Login into Docker Hub
          command: |
            echo "$DOCKER_PWD" | docker login --username "$DOCKER_USER" --password-stdin
