apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Script-Name /pgadmin;
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-cluster-ip-service
                port:
                  number: 9090
          - path: /pgadmin/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: pgadmin-cluster-ip-service
                port:
                  number: 5050
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: app-cluster-ip-service
                port:
                  number: 4040
