FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --silent

COPY ./ ./

RUN npm run build --prod

FROM nginx:alpine

EXPOSE 80

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist/quiz-stream/browser /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]