FROM node:20-alpine

EXPOSE 80

WORKDIR /app

COPY package*.json ./

RUN npm install --silent

RUN npm install -g @angular/cli

COPY ./ ./

RUN ng analytics off

ENTRYPOINT ["sh", "-c", "node replace-env.js && npm run start -- --port 80 --host 0.0.0.0"]