spring:
  jpa:
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
      poll-interval: 2s
      quiet-period: 1s
      enabled: true
    livereload:
      enabled: true
