spring:
  jpa:
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
      poll-interval: 2s
      quiet-period: 1s
      enabled: true
    livereload:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/v1/actuator
  endpoint:
    health:
      show-details: always
    # env:
    #   show-values: always
    #   keys-to-sanitize:
  info:
    env:
      enabled: true