spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time-zone: America/Santiago

  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED:true}

server:
  port: ${SERVER_PORT:9090}
  address: 0.0.0.0

springdoc:
  api-docs:
    enabled: true
