FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /tmp

COPY pom.xml ./

RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine

EXPOSE 9090

WORKDIR /api

COPY --from=build /tmp/target/*.jar ./quizstream-api.jar

# Run the application
CMD ["java", "-jar", "quizstream-api.jar"]
