FROM maven:3.9-eclipse-temurin-21

EXPOSE 9090

WORKDIR /api

COPY pom.xml .

RUN mvn dependency:go-offline -B

COPY ./src ./src

COPY ./wait-for-it.sh ./wait-for-it.sh

RUN chmod +x wait-for-it.sh

ENTRYPOINT ["./wait-for-it.sh", "postgres:5432", "--timeout=60", "--", "mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
